name: om4labs
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - black
  - cartopy
  - dask
  - intake-xarray
  - esmf=8.0.0
  - esmpy=8.0.0
  - matplotlib
  - mpich
  - netcdf4
  - numpy
  - numba
  - palettable
  - pyshp
  - pytest
  - regionmask
  - scipy
  - shapely
  - six
  - xarray
  - xesmf=0.6.2
  - xgcm
